const listaPalavras = [
    [
        'BRASIL',
        'JAPAO',
        'AUSTRALIA',
        'CANADA',
        'ITALIA',
        'RUSSIA',
        'EGITO',
        'ARGENTINA',
        'INDIA',
        'CHINA'
    ],
    [
        'AZUL',
        'VERDE',
        'AMARELO',
        'VERMELHO',
        'LARANJA',
        'ROXO',
        'ROSA',
        'MARROM',
        'CINZA',
        'PRETO'
    ],
    [
        'KIWI',
        `BANANA`,
        'ABACAXI',
        'MORANGO',
        `UVAS`,
        `PERA`,
        'MELANCIA',
        `PESSEGO`,
        'LIMAO',
        'MANGA'
    ],
    [
        'ELEFANTE',
        'GIRAFA',
        'LEAO',
        'TIGRE',
        'GATO',
        'CACHORRO',
        'PANDA',
        'PINGUIM',
        'COBRA',
        'BORBOLETA'
    ],
    [
        'MEDICO',
        'PROFESSOR',
        'BOMBEIRO',
        'POLICIAL',
        'ENFERMEIRO',
        'ARTISTA',
        'JORNALISTA',
        'PILOTO',
        'ARQUITETO',
        'COZINHEIRO'
    ]
];

module.exports = listaPalavras;